"""empty message

Revision ID: 5301350542ab
Revises: 33f1ee94f2d9
Create Date: 2022-05-31 19:11:06.617503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5301350542ab'
down_revision = '33f1ee94f2d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('website_link', sa.String(length=100), nullable=True))
    op.add_column('artist', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    op.alter_column('artist', 'genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('artist', 'seeking_venue',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_column('artist', 'artist_website_address')
    op.add_column('venue', sa.Column('website_link', sa.String(length=100), nullable=True))
    op.add_column('venue', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('genres', sa.PickleType(), nullable=False))
    op.alter_column('venue', 'seeking_talent',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_column('venue', 'past_shows')
    op.drop_column('venue', 'num_upcoming_show')
    op.drop_column('venue', 'website_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('website_address', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('venue', sa.Column('num_upcoming_show', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('venue', sa.Column('past_shows', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.alter_column('venue', 'seeking_talent',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_column('venue', 'genres')
    op.drop_column('venue', 'seeking_description')
    op.drop_column('venue', 'website_link')
    op.add_column('artist', sa.Column('artist_website_address', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.alter_column('artist', 'seeking_venue',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('artist', 'genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_column('artist', 'seeking_description')
    op.drop_column('artist', 'website_link')
    # ### end Alembic commands ###
